services:
    liip_search.google:
        class: Liip\SearchBundle\Controller\GoogleSearchController
        arguments:
            google_xml_search: "@liip_search.google.xml_api_search"
            templating_engine: "@templating"
            results_per_page: "%liip_search.results_per_page%"
            restrict_by_language: "%liip_search.restrict_by_language%"
            translation_domain: "%liip_search.translation_domain%"
            page_param_name: "%liip_search.page_param_name%"
            query_param_name: "%liip_search.query_param_name%"
            search_route: "%liip_search.search_route%"

    liip_search.google.xml_api_search:
        class: Liip\SearchBundle\Google\GoogleXMLSearch
        arguments:
            google_search_key: "%liip_search.google.search_key%"
            restrict_to_site:  "%liip_search.google.restrict_to_site%"
            restrict_to_labels: "%liip_search.google.restrict_to_labels%"
