liip_search:
    pattern: /search
    defaults: { _controller: liip_search.google:searchAction }

liip_searchbox:
    pattern: /searchbox
    defaults: {_controller: liip_search_default_controller:showSearchBoxAction}

# TODO: remove when we drop symfony 2.1 support
liip_search_paging:
    pattern: /_searchpaging
    defaults: {_controller: liip_search_default_controller:showPagingAction}