services:
    liip_search_pager:
        class: Liip\SearchBundle\Pager\Pager
        arguments:
            router: "@router"
            search_route: "%liip_search.search_route%"
            max_head_items: "%liip_search.pager_max_head_items%"
            max_tail_items: "%liip_search.pager_max_tail_items%"
            max_adjoining_items: "%liip_search.pager_max_adjoining_items%"
            query_param_name: "%liip_search.query_param_name%"
            page_param_name: "%liip_search.page_param_name%"

    liip_search_default_controller:
        class: Liip\SearchBundle\Controller\DefaultController
        arguments:
            templating_engine: "@templating"
            router: "@router"
            pager: "@liip_search_pager"
            translation_domain: "%liip_search.translation_domain%"
            query_param_name: "%liip_search.query_param_name%"
            search_route: "%liip_search.search_route%"
