services:
    liip_search.pager:
        class: Liip\SearchBundle\Pager\Pager
        arguments:
            - "@router"
            - "%liip_search.search_route%"
            - "%liip_search.pager.max_head_items%"
            - "%liip_search.pager.max_tail_items%"
            - "%liip_search.pager.max_adjoining_items%"

    liip_search.controller.search:
        class: Liip\SearchBundle\Controller\SearchController
        arguments:
            - "@liip_search.default_search_client"
            - "@templating"
            - "@router"
            - "@liip_search.pager"
            - "%liip_search.controller.options%"
